name: LanguageTransfer
options:
  bundleIdPrefix: com.grafton
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  developmentLanguage: en

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.0.0

settings:
  base:
    DEVELOPMENT_TEAM: B5X96QDRF4
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "6.0"
    VERSIONING_SYSTEM: apple-generic
    CURRENT_PROJECT_VERSION: "9"
    MARKETING_VERSION: "1.0"

targets:
  LanguageTransfer:
    type: application
    platform: iOS
    sources:
      - path: LanguageTransfer
        excludes:
          - "GoogleService-Info.plist"
      - path: LanguageTransfer/GoogleService-Info.plist
        buildPhase: resources
    dependencies:
      - package: Firebase
        products:
          - FirebaseAnalytics
          - FirebaseCrashlytics
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.grafton.languagetransfer.spanish
        INFOPLIST_FILE: LanguageTransfer/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: B5X96QDRF4
